### PR TITLE
Update EA docker files for Nov 24 preview 1

### PR DESCRIPTION
**Pull request by ramachandrabolisetti**
OE jdk11,17 Docker files are updated for EA Nov 24 preview 1
@jayasg12 FYI

### CODE REVIEW

**Comment by ramachandrabolisetti** [comment]
@tajila could you please review this.

**Review by jayasg12 — COMMENTED** [review]
@ramachandrabolisetti Please confirm that you removed the copy of LICENSE file since it is not in java.base ?

**Comment by ramachandrabolisetti** [comment]
@jayasg12 yes, removed the LICENSE file copy in this commit https://github.com/ibmruntimes/semeru-containers/pull/130/commits/604eafe46c8248d39ceb6fc3182d9a229c10f513.

**Review by tajila — APPROVED** [review]
Ubuntu changes look good. Why are you removing the CRIU code from the UBI-min files? We dont need it for this release but just curious.

**Comment by ramachandrabolisetti** [comment]
I picked the latest open docker files and created these EA files, as there is no CRIU code used there it might be reflecting as removed.

**Pull request merged**
