### PR TITLE
Update Tomcat download link

### PR DESCRIPTION
**Pull request by LongyuZhang**
- Update Tomcat download link
- Related Issue: runtime_infra 8340

### CODE REVIEW

**Comment by LongyuZhang** [comment]
Test Link:
- criu_pingPerf_testCreateImageAndUnprivilegedRestore_ubi8 test (link hyc_grinder/36412), which first use this dockerfile to build Semeru container image, then further build OpenLiberty image for pingperf test.

**Review by AdamBrousseau — APPROVED** [review]
LFTM. @narkedi are we able to test this at all?

**Comment by narkedi** [comment]
We did test it by replacing the link and still see some intermittent failures.

**Comment by ramachandrabolisetti** [comment]
> We did test it by replacing the link and still see some intermittent failures.

Tested on our servers with https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.83/bin/apache-tomcat-9.0.83.tar.gz and able to fetch the file. No issues seen.

**Comment by narkedi** [comment]
@AdamBrousseau Based on the input, as the link work fine, this PR is good to be merged.

**Pull request merged**
